[package]
name = "doro"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "terminal pomodoro timer"
homepage = "https://raafay.world/projects/doro"
repository = "https://github.com/rraafays/doro"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
colored = "2.0.0"
